import type { Metadata } from "next";
import localFont from "next/font/local";
import { I18nProvider } from "@/components/provider/i18n";
import { Navigation } from "@/components/layout/Navigation";
import { Footer } from "@/components/layout/Footer";
import "./../globals.css";

const pretendard = localFont({
  src: "../../../public/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}) {
  const { lang } = await params;
  const displayLang = lang ?? "ko";

  return (
    <html lang={displayLang} className="h-full antialiased">
      <body
        className={`flex flex-col min-h-full pt-[64px] ${pretendard.className} text-black`}
      >
        <I18nProvider lang={displayLang}>
          <Navigation />

          <main className="flex-1">{children}</main>

          <Footer />
        </I18nProvider>
      </body>
    </html>
  );
}
