import type { Metadata } from "next";
import localFont from "next/font/local";
import { Navigation } from "@/components/layout/Navigation";
import "./globals.css";
import { Footer } from "@/components/layout/Footer";

const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="h-full antialiased">
      <body
        className={`flex flex-col min-h-full pt-[64px] ${pretendard.className} text-black`}
      >
        <Navigation />

        <main className="flex-1">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
